version: '2'
services:
    emtest-app:
        image: emtest
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://emtest-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=EmTest
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    emtest-mongodb:
        extends:
            file: mongodb.yml
            service: emtest-mongodb
